name: Simple Test Workflow

on:
  push:
    branches:
      - blog

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World! The workflow has triggered successfully!"